#%RAML 1.0 NamedExample

value:

 - 
  flight_id: 10001
  flight_name: G8-336
  flight_source: DEL
  flight_destination: MUM
  flight_date: 2021-11-24T03:30:00
  flight_fare: 5000
  flight_availableSeats: 180

 -
  flight_id: 10002
  flight_name: G8-337
  flight_source: LKO
  flight_destination: CHN
  flight_date: 2021-11-16T04:30:00
  flight_fare: 6000
  flight_availableSeats: 180